server:
  port: 8081

spring:
  application:
    name: aluno-academia

  datasource:
    url: jdbc:mysql://localhost:3306/academia?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true